# Generated by Django 3.1.1 on 2020-09-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=20)),
                ('ssh_pub_key', models.TextField(blank=True, null=True)),
                ('ssh_priv_key', models.TextField(blank=True, null=True)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(default='', max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
