# Generated by Django 3.1.1 on 2020-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ssh_pub',
            field=models.TextField(default=''),
        ),
    ]
