# Generated by Django 3.1.1 on 2020-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='action',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='command',
            name='sudo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.TextField(null=True),
        ),
    ]
