# Generated by Django 3.1.1 on 2020-09-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
