# Generated by Django 3.1.1 on 2020-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_command_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='output',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
