version: '3.3'

services:
  api:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./environ/dev.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=linux_manager
      - POSTGRES_PASSWORD=l!nux_m@n@g3r

volumes:
  postgres_data: